#!/bin/bash

# Config Installer
# Rik Brugman 2018

# Files to work with
CONFIGURATIONS=(
	pictures/background.jpg
	.bashrc
	.bash_profile
	bin/player-status
	bin/docker-status
	bin/vlc-stream-status
	bin/startup
	.gtkrc-2.0
	.vimrc
	.config/compton.conf
	.config/dunst
	.config/i3
	.config/polybar/config
	.config/polybar/globalConfig
	.config/powerline
	.config/gtk-3.0
	.xinitrc
	.Xresources
	.xbindkeysrc
)

# Working Dir
SOURCE_DIR=$(pwd)/src
WORKING_DIR=/home/$USER

# System Colors
C_ERR="$( tput setaf 1 )"
C_SUCCESS="$( tput setaf 2 )"
C_WARNING="$( tput setaf 3 )"
C_INFO="$( tput setaf 6 )"
C_DEFAULT="$( tput sgr0 )"

# Others
HOST=$(hostname)

function create_symlink() {
	SOURCE=$SOURCE_DIR/$1
	DEST=$WORKING_DIR/$1
	SERVING_TYPE='global'

	if [ -e $SOURCE_DIR/$HOST/$1 ]; then
		SOURCE=$SOURCE_DIR/$HOST/$1
		SERVING_TYPE='specific'
	fi

	echo -e "  ➜ Copying $1 ($SERVING_TYPE)..."

	# file does not exist in repo
	if [ ! -e $SOURCE ]; then
		echo -e "    ${C_ERR}⨯ This file does not exist in source. Skipping...${C_DEFAULT}"
		return
	fi

	# create dir if needed
	if [ ! -d $(dirname $DEST) ]; then
		mkdir $(dirname $DEST)
	fi

	# check if exists in destination and is not a symlink
	if [[ -e $DEST || -L $DEST ]]; then
		echo -e "    ${C_ERR}⨯ File or symlink already exists. Skipping...${C_DEFAULT}"
		return;
	fi

	# link file
	ln -s $SOURCE $DEST
	echo -e "    ${C_SUCCESS}✓ File copied${C_DEFAULT}"
}

# make copies
for file in "${CONFIGURATIONS[@]}"
do
	create_symlink $file
done
